name: batchfilerename
version: '1.0'
summary: Batch file renaming utility
description: |
  Batch file rename is a simple tool to rename multiple files at once by find/replace

base: core18
grade: stable
confinement: strict
icon: batchfilerename/img/logo.png

apps:
  batchfilerename:
    command: desktop-launch $SNAP/bin/batchfilerename
    plugs: [desktop,desktop-legacy,unity7,home]

parts:
  batchfilerename:
    plugin: python
    source: .
    stage-packages:
      [python3-tk,fontconfig-config,fonts-dejavu-extra]
    after: [desktop-glib-only]

  desktop-glib-only:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: glib-only
      plugin: make
      build-packages:
        - libglib2.0-dev
      stage-packages:
        - libglib2.0-bin

layout:
  /usr/share/tcltk:
    bind: $SNAP/usr/share/tcltk
  /usr/lib/tcltk:
    bind: $SNAP/usr/lib/tcltk
